Selivanovskaya Daria [18PMI-2] lab3
geexie/llvm-project pull request #91
Opened 2021-04-06 16:05 UTC by dselivanovskaya

2021-04-12 18:46 UTC, geexie requested changes
@dselivanovskaya, please rebase on top of hse-21 branch to resolve merge conflicts

2021-04-14 08:50 UTC, dselivanovskaya commented
@geexie, Я не понимаю что нужно сделать :(

2021-04-14 11:13 UTC, geexie commented
> @geexie, Я не понимаю что нужно сделать :(

Хорошо, поняла Вас. Я покажу на практике

2021-04-17 23:29 UTC, geexie commented
@dselivanovskaya, закрываю потому-как помержила из командной строки. Зачтено

2021-04-17 23:29 UTC, closed without merging